Provide an initial implementation
uisautomation/iar-gatherstats pull request #1
Opened 2018-05-10 10:41 UTC by rjw57

This PR populates this repo with some code. It is best reviewed commit wise.

Some commits merely prepare the ground for the implementation:

* Commit 8eb99b1 strips out web-related functionality from the default boilerplate template and provides a simple "stub" management command, ``gatherstas`` which does nothing other than print ``Hello, world`` to the console.
* Commits e99a75a, c5fa905 and fee8dbe are essentially "plumbing" commits which change some small bit of configuration or install useful packages in the Docker images.

The bulk of the implementation is contained in commits 4da7e61, 04fbf48 and 7148d39:

* Commit 4da7e61 adds a new database model for recording a single statistic.
* Commit 04fbf48 adds functionality to atomically create Statistic models from a single response from the gatherstats endpoint.
* Commit 7148d39 implements the ``gatherstats`` management command which fetches the stats response and uses the functionality in 04fbf48 to update the database.

Travis has been configured at https://travis-ci.org/uisautomation/iar-gatherstats.

Docker hub has been configured with an automatically built image at https://hub.docker.com/r/uisautomation/iar-gatherstats/.

And example of the documentation built from this PR is at https://rjw57.github.io/iar-gatherstats/.

2018-05-10 10:47 UTC, rjw57 commented
This PR does not update uisautomation/iar-deploy. That part of the story has moved to uisautomation/iar-deploy#34.

2018-05-17 13:08 UTC, msb requested changes

2018-05-17 13:08 UTC, msb commented on gatherstats/models.py
> +            models.Index(fields=['endpoint']),
as discussed - this can be removed

2018-05-17 13:08 UTC, msb commented on gatherstats/models.py
> +    def create_from_stats_response(self, endpoint, body, fetched_at=None):
could you use ``.., fetched_at=timezone.now()):`` ?

2018-05-17 13:08 UTC, msb commented on README.md
> +
as discussed - add minimal commands for the creation/migration of a DB (either postgres or sqlite - don't mind)

2018-05-18 09:24 UTC, rjw57 commented on gatherstats/models.py
> +    def create_from_stats_response(self, endpoint, body, fetched_at=None):
No, because the ``create_from_stats_response()`` almost certainly is not simultaneous with the fetch. By design, I want the caller to be explicit about what time they actually fetched the endpoint at.

2018-05-18 09:37 UTC, rjw57 commented on gatherstats/models.py
> +    def create_from_stats_response(self, endpoint, body, fetched_at=None):
... and, additionally, I *think* that would make the default fetched_at time to be the time the module was first imported.

2018-05-18 09:48 UTC, merged